### ISSUE TITLE
allow specifying start element

### ISSUE THREAD

**Issue by VladimirAlexiev** [epiasini/XSDtoRNG#11]
I'm trying to convert http://www.lido-schema.org/schema/v1.0/lido-v1.0.xsd. The starting element for that schema is lidoWrap, as you can see here http://www.lido-schema.org/schema/v1.0/lido-v1.0-schema-listing.html. But afaik, this is not indicated anywhere in the schema.

So I changed the xsl to allow specifying the starting element as a param **start**, eg:
```sh
xsltproc -stringparam start lidoWrap -o lido-v1.0.rng c:\prog\bin\XSDtoRNG.xsl lido-v1.0.xsd
```
Will submit patch

**Comment by VladimirAlexiev** [comment]
The fix is not good. jing gives this error:
lido-v1.0.rng:197:45: error: found "element" element but expected "define" or "start" or "include" or "div" element

So more changes are needed to change non-starting elements to **define**, and to use them with **ref**

**Comment by ndebeiss** [comment]
That schema is a strange mix of "Salami Slice" and "Venetian Blind", some elements are defined at top level like Salami Slice and the content of the elements are defined as types like Venetian Blind.

The issue with Salami Slice is that I cannot know which one is the top level tag. Try with the correction of your commit I suggest, and I will integrate it to the code.

Thank you very much for the issue reporting and fixes.

**Comment by VladimirAlexiev** [comment]
The parentheses in the if are not the problem.
I just committed a better fix: https://github.com/VladimirAlexiev/XSDtoRNG/commit/3239c2326081c37abdd9ddf3a79ddc35ef6183af.
Hmm, can you pull this or should I do something extra toe nable you to pull it?

**Comment by ndebeiss** [comment]
Ok I think I got the whole case. If the element declaration is at the top of the schema, then in any case it must me surrounded by a rng:define.
Then with the start parameter, we can decide if it is the top element or not.
I prefer spliting totally the case "at the top of the schema" and the other cases, like in my fix.
