### ISSUE TITLE
XSD or RNG to JSON Schema?

### ISSUE THREAD

**Issue by coderextreme** [epiasini/XSDtoRNG#19]
I would like to validate complex hierarchical JSON documents against XSD, RNG, or JSON schema.  Should I create a JSON schema, or work towards validating the JSON with XSD or RNG?  Thanks.

**Comment by ndebeiss** [comment]
If you find a standard for json schema, go for it, otherwise, translate the json to XML and use the XML schema language you want. XSD is far more complex than RNG, as it has been writtenin order to describe an object mapping
