### ISSUE TITLE
Error converting IP-XACT schema

### ISSUE THREAD

**Issue by epiasini** [epiasini/XSDtoRNG#5]
_Original author: andreas....@hiced.com (December 08, 2011 15:47:26)_

Trying to convert IP-XACT xsd schemas v1.4 to RNG (schemas can be found at http://www.accellera.org)

Fails at a few files.

Regards
Andreas

_Original issue: http://code.google.com/p/xsdtorngconverter/issues/detail?id=5_

**Comment by ndebeiss** [comment]
no example
