### ISSUE TITLE
Cannot convert XSD restriction into RNG

### ISSUE THREAD

**Issue by epiasini** [epiasini/XSDtoRNG#6]
_Original author: midhat...@gmail.com (July 03, 2013 13:05:19)_

Target XSD: https://www.oasis-open.org/committees/uddi-spec/doc/spec/v3/schema/uddi_v3.xsd
This XSD is valid and validates against the XSD and RNG schemas of XML Schema, but the generated RNG is not valid. Specifically we have problems like this:

        &lt;xsd:simpleType name=&quot;completionStatus&quot; final=&quot;restriction&quot;&gt;
                &lt;xsd:restriction base=&quot;xsd:string&quot;&gt;
                        &lt;xsd:maxLength value=&quot;32&quot;/&gt;
                        &lt;xsd:whiteSpace value=&quot;collapse&quot;/&gt;
                        &lt;xsd:enumeration value=&quot;status:complete&quot;/&gt;
                        &lt;xsd:enumeration value=&quot;status:fromKey_incomplete&quot;/&gt;
                        &lt;xsd:enumeration value=&quot;status:toKey_incomplete&quot;/&gt;
                        &lt;xsd:enumeration value=&quot;status:both_incomplete&quot;/&gt;
                &lt;/xsd:restriction&gt;
        &lt;/xsd:simpleType&gt;

Becomes
        &lt;rng:define name=&quot;completionStatus&quot;&gt;
                &lt;rng:choice&gt;
                        &lt;rng:param name=&quot;maxLength&quot;&gt;32&lt;/rng:param&gt;
                        &lt;rng:param name=&quot;whiteSpace&quot;&gt;collapse&lt;/rng:param&gt;
                        &lt;rng:value&gt;status:complete&lt;/rng:value&gt;
                        &lt;rng:value&gt;status:fromKey_incomplete&lt;/rng:value&gt;
                        &lt;rng:value&gt;status:toKey_incomplete&lt;/rng:value&gt;
                        &lt;rng:value&gt;status:both_incomplete&lt;/rng:value&gt;
                &lt;/rng:choice&gt;
        &lt;/rng:define&gt;

Which fails validation because of the param tags. 

This was discovered using the online tool at http://debeissat.nicolas.free.fr/XSDtoRNG.php

_Original issue: http://code.google.com/p/xsdtorngconverter/issues/detail?id=7_

**Comment by ndebeiss** [comment]
This is solved by fix #9  which only creates rng:param tags inside a rng:data tag.
