### ISSUE TITLE
extra attributes should be outside of rng:data 

### ISSUE THREAD

**Issue by VladimirAlexiev** [epiasini/XSDtoRNG#9]
I'm trying to convert http://www.lido-schema.org/schema/v1.0/lido-v1.0.xsd.
This XSD
```xsd
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute ref="lido:pref"/>
							<xsd:attribute ref="xml:lang"/>
							<xsd:attribute ref="lido:encodinganalog"/>
							<xsd:attribute ref="lido:label"/>
						</xsd:extension>
					</xsd:simpleContent>
```
gets converted to this RNG
```xml
<rng:data type="string">
  <rng:ref name="attr_pref"/>
  <rng:ref name="attr_lang"/>
  <rng:ref name="attr_encodinganalog"/>
  <rng:ref name="attr_label"/>
</rng:data>
```
and jing complains: lido-v1.0.rng:228:58: error: only "param" and "except" child elements are allowed.

Looking at http://relaxng.org/tutorial-20011203.html#IDA5UYR, the correct way is to put the attributes outside the datatype:
```xml
  <rng:data type="string"/>
  <rng:ref name="attr_pref"/>
  <rng:ref name="attr_lang"/>
  <rng:ref name="attr_encodinganalog"/>
  <rng:ref name="attr_label"/>
```
The patch is very simple, will post it now

**Comment by VladimirAlexiev** [comment]
Unfortunately the fix is incomplete.
If the nested element is "pattern" or "except", it should be INSIDE rng:data.

**Comment by VladimirAlexiev** [comment]
Hi @ndebeiss, please try your fix on the LIDO schema.
After converting to rng, I comment out lines 59-60 because converting XML and OpenGIS is quite difficult; then validate with jing
```xml
	<!--rng:include href="http://www.w3.org/2001/03/xml.rng" ns="http://www.w3.org/XML/1998/namespace"/-->
	<!--rng:include href="http://schemas.opengis.net/gml/3.1.1/base/feature.rng" ns="http://www.opengis.net/gml"/-->
```

Your fix copies text content outside of a:documentation:
```xml
	<rng:define name="attr_geographicalEntity"><rng:optional><rng:attribute name="geographicalEntity"><rng:data type="string">
			Definition: Qualifies the type of the given place entity according to geographical structures. 
			How to record: Data values can include: natural environment, landscape.
		</rng:data><a:documentation>
			Definition: Qualifies the type of the given place entity according to geographical structures. 
			How to record: Data values can include: natural environment, landscape.
		</a:documentation></rng:attribute></rng:optional></rng:define>
```
and then jing complains many times:
lido-v1.0.rng:637:75: error: illegal characters ignored

**Comment by ndebeiss** [comment]
Yes that is a regression. Can you try with that fix please ?

**Comment by VladimirAlexiev** [comment]
That is much better!

However, a problem remains with the special handling of XML attributes (eg xml:lang).
A fragment like
```xsd
		<xsd:attribute ref="xml:lang" use="required"/>
```
is transformed to
```xsd
		<rng:attribute name="lang" ns="http://www.w3.org/XML/1998/namespace"><rng:value type="language"/></rng:attribute>
```
and causes this error:
lido-v1.0.rng:214:100: error: "" is not a valid value of the datatype

The same happens no matter if I refer to a local xml.rng 
```xml
	<rng:include href="c:/my/.emacs.d/nxml-schemas/xml.rng" ns="http://www.w3.org/XML/1998/namespace"/>
```
or I comment it out

**Comment by ndebeiss** [comment]
Right, it seems the expected syntax is rng:data instead of rng:value. Fixed
?

2015-07-01 11:34 GMT+02:00 Vladimir Alexiev notifications@github.com:

**Comment by VladimirAlexiev** [comment]
yes!
